const WHATSAPP_NUMBER = '573246684446';
const WHATSAPP_DISPLAY_PHONE = '+57 324 668 4446';
const WHATSAPP_MESSAGE = 'Quisiera más información!';
const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`;
const WHATSAPP_PHONE_LINK = `tel:+${WHATSAPP_NUMBER}`;

export { WHATSAPP_NUMBER, WHATSAPP_DISPLAY_PHONE, WHATSAPP_MESSAGE, WHATSAPP_URL, WHATSAPP_PHONE_LINK };
